import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import '@/styles/globals.css'
import ReactQuery from '@/libs/providers/react-query'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={openSans.className}>
        <main className='mx-auto w-full px-4 py-10 lg:w-1/3'>
          <ReactQuery>{children}</ReactQuery>
        </main>
      </body>
    </html>
  )
}
