import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import ReactQuery from '@/libs/providers/react-query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='w-full lg:w-1/3 mx-auto py-4'>
          <ReactQuery>{children}</ReactQuery>
        </main>
      </body>
    </html>
  )
}
